### ISSUE TITLE
userName 검색기능 구현

### ISSUE THREAD

**Issue by kjungit** [KDT4-team6/Paldo#33]
거래 내역 관리에서 user이름으로 검색기능을 테스트 하려고 합니다!
현재 나오는 거래내역에서 user가 1개밖에 되지 않아 테스트할 수 없습니다ㅠㅠ
다른 user이름으로 2~3개정도 회원가입 후 거래내역이 남도록 해주세요!
@yousunzoo @bongsee

**Comment by yousunzoo** [comment]
주무...세요...
아침에 아이디 새로 만들어놓을테니까 그후에 봉석님이 구매내역 만들어주시면 될 것 같습니다!

**Comment by kjungit** [comment]
테스트 완료 하였습니다.
